version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    env_file: .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - "./src:/usr/src/app/src"
      - "./logs:/usr/src/app/logs"
    links:
      - "postgres:postgres"
    depends_on:
      - postgres
    env_file: .env