export const HTTP_CODE_FORBIDDEN = 403;
export const HTTP_CODE_SUCCESS = 200;
export const HTTP_CODE_SERVER_ERROR = 500;
export const HTTP_CODE_BAD_REQUEST = 400;
export const HTTP_CODE_CREATED = 201;
export const HTTP_CODE_AUTHORIZATION_REQUIRED = 401;