import 'dotenv/config';

const {
	POSTGRES_PASSWORD,
	POSTGRES_USER,
	POSTGRES_DB,
	POSTGRES_HOST,
	API_PORT,
	NODE_ENV,
	USER_TOKEN_SECRET_KEY,
	USER_TOKEN_EXPIRES_HOURS
} = process.env;

const USER_PASSWORD_SALT_ROUNDS = Number.parseInt(process.env.USER_PASSWORD_SALT_ROUNDS);

export {
	POSTGRES_PASSWORD,
	POSTGRES_USER,
	POSTGRES_HOST,
	POSTGRES_DB,
	API_PORT,
	NODE_ENV,
	USER_PASSWORD_SALT_ROUNDS,
	USER_TOKEN_SECRET_KEY,
	USER_TOKEN_EXPIRES_HOURS
};