import 'dotenv/config';

let {
	API_PORT,
	NODE_ENV,
	POSTGRES_DB,
	POSTGRES_HOST,
	POSTGRES_PASSWORD,
	POSTGRES_USER,
	USER_PASSWORD_SALT_ROUNDS,
	USER_TOKEN_EXPIRES_HOURS,
	USER_TOKEN_SECRET_KEY
} = process.env;

USER_PASSWORD_SALT_ROUNDS = Number.parseInt(USER_PASSWORD_SALT_ROUNDS);

export {
	API_PORT,
	NODE_ENV,
	POSTGRES_DB,
	POSTGRES_HOST,
	POSTGRES_PASSWORD,
	POSTGRES_USER,
	USER_PASSWORD_SALT_ROUNDS,
	USER_TOKEN_EXPIRES_HOURS,
	USER_TOKEN_SECRET_KEY
};